#logging.level.root=DEBUG

spring:
  task:
    scheduling:
      pool:
        size: 10
  mvc:
    async:
      request-timeout: 3600000

server:
  port: 7000
  compression:
    enabled: true
    mime-types: text/html,text/plain,text/css,application/javascript,application/json
    min-response-size: 1024

languages:
  en:
    name: English
    direction: ltr

rootURL: http://localhost:3000/

colours:
  Twitter: "#1d9cf0"
  YouTube: "#cc0000"
  Telegram: "#ddaf24"
  Mastodon: "#5945d9"
  Website: "#2ca02c"
  TikTok: "#00f2ea"
  Facebook: "#3b5998"
  Instagram: "#c32aa3"
